spring:
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    enabled: true
    default-schema: public
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:

      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true